services:
  # Application server 172.18.0.2
  server:
    image: server
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080/tcp"
    expose:
      - 8080/tcp
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://postgres:postgres@db:5432/go_restful?sslmode=disable
    volumes:
      - /tmp/app:/var/log/app
    depends_on:
      db:
        condition: service_healthy
  # Database service 172.18.0.3
  db:
    image: postgres:15-alpine
    container_name: go-rest-api-db
    restart: always
    ports:
      - "5432:5432/tcp"
    expose:
      - "5432/tcp"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "go_restful"
    volumes:
      - ./testdata/postgres:/var/lib/postgresql/data
      - ./testdata:/testdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
